---
title: "Tema 3"
author: "Marcelino Martínez"
date: "`r Sys.Date()`"
output:
  word_document:
    toc: yes
    toc_depth: '3'
  html_notebook:
    echo: yes
    number_sections: yes
    toc: yes
  pdf_document:
    toc: yes
    toc_depth: 3
    number_sections: yes
  html_document:
    echo: yes
    number_sections: yes
    theme: lumen
    toc: yes
params:
  lang: ES
lang: "`r switch(params$lang, ES = 'es-ES', EN = 'en-US')`"
subtitle: "Tratamiento de Datos. Grado en Ciencia de Datos- UV"
language:
  label:
    fig: 'Figura '
    tab: 'Tabla '
    eq: 'Ecuación '
    thm: 'Teorema '
    lem: 'Lema '
    def: 'Definición '
    cor: 'Corolario '
    prp: 'Proposición '
    exm: 'Ejemplo '
    exr: 'Ejercicio '
    proof: 'Demostración. '
    remark: 'Nota: '
    solution: 'Solución. '
---

## Ejemplo 23. Imagen covid.
```{r}
library(readr)
owid_covid_data <- read_csv("owid-covid-data.csv")

data(owid_covid_data)
        library(ggplot2)
        ggplot(owid_covid_data, aes(x=location)) +
               geom_line(aes(y=total_cases))
        
caudal <- ggplot(owid_covid_data, aes(x = date)) + geom_line(aes(y = 'Canada'), color = "red") + geom_line(aes(y = 'Italy'), col = "blue") + labs(title = "Caudales de ambos rios a lo largo del tiempo")
caudal

```

```{r}

covid_data <- read_csv("owid-covid-data.csv")

data_seleccion <- covid_data %>% 
  filter(location %in% c("United States", "Italy", "France", "Germany", "Canada", "Japan", "United Kingdom", "Spain"))

data_seleccion2 <- select(data_seleccion, location, date, new_deaths_smoothed_per_million)

colores <- c("United States" = "purple","Italy" = "blue", "France" = "red", "Germany" = "green", "Canada" = "dark red","Japan" = "dark blue", "United Kingdom" = "pink", "Spain" =  "black")

ggplot(data = data_seleccion2, aes(x = date, y = new_deaths_smoothed_per_million, color = location,, group = location)) + 
  geom_line() + 
  geom_path() + 
  scale_y_continuous(breaks = seq(0, 18, by = 2)) +
  scale_color_manual(values = colores) +
  geom_line(data = filter(data_seleccion2, location == "Spain"), size = 1.5)
  
```


















